apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      type: db
      service: db-service
  template:
    metadata:
      labels:
        type: db
        service: db-service
        db: mysql
    spec:
      containers:
      - name: db
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "qwertyuiop"
        - name: MYSQL_USER
          value: "iiitbspring"
        - name: MYSQL_PASSWORD
          value: "iiitbspring"
        - name: MYSQL_DATABASE
          value: "foody"
        ports:
        - containerPort: 3306
 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      type: server-microservice
      service: api-server-service
  template:
    metadata:
      labels:
        type: server-microservice
        service: api-server-service
        framework: spring-boot
        language: java
    spec:
      containers:
      - name: api-server
        image: vivekmt2019137/foodyserver:latest
        env:
        - name: username
          value: "iiitbspring"
        - name: password
          value: "iiitbspring"
        - name: DB_URL
          value: "jdbc:mysql://db-service:3306?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
        ports:
        - containerPort: 8686
        livenessProbe:
          httpGet:
            path: /api/foods
            port: 8686
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8686
          periodSeconds: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      type: app
      service: app-service
  template:
    metadata:
      labels:
        type: app
        service: app-service
        framework: angular
        language: typescript
    spec:
      containers:
      - name: app
        image: vivekmt2019137/app:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  ports:
  - port: 3306
  selector:
    type: db
    service: db-service

---

apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  loadBalancerIP: 20.193.159.33
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 80
  selector:
    type: app
    service: app-service

---


apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  loadBalancerIP: 20.193.159.62
  type: LoadBalancer
  ports:
  - name: api
    port: 8686
    targetPort: 8686
  selector:
    type: server-microservice
    service: api-server-service