apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      type: db
      service: db-service
  template:
    metadata:
      labels:
        type: db
        service: db-service
        db: mysql
    spec:
      containers:
      - name: db
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "qwertyuiop"
        - name: MYSQL_USER
          value: "iiitbspring"
        - name: MYSQL_PASSWORD
          value: "iiitbspring"
        - name: MYSQL_DATABASE
          value: "foody"
        ports:
        - containerPort: 3306


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      type: server-microservice
      service: api-server-service
  template:
    metadata:
      labels:
        type: server-microservice
        service: api-server-service
        framework: spring-boot
        language: java
    spec:
      containers:
      - name: api-server
        image: vivekmt2019137/foodyserver:2
        env:
        - name: username
          value: "iiitbspring"
        - name: password
          value: "iiitbspring"
        - name: DB_URL
          value: "jdbc:mysql://db-service:3306?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
        ports:
        - containerPort: 4444
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 4444
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 4444
          periodSeconds: 1

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  ports:
  - port: 3306
  selector:
    type: db
    service: db-service

---


apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  type: LoadBalancer
  ports:
  - port: 4444
  selector:
    type: server-microservice
    service: api-server-service