apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out ./k8s/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out ./k8s/
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/database: "true"
        io.kompose.service: server
    spec:
      containers:
        - env:
            - name: DB_URL
              value: jdbc:mysql://db:3306?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
            - name: password
              value: iiitbspring
            - name: username
              value: iiitbspring
          image: vivekmt2019137/foodyserver:1
          name: server
          ports:
            - containerPort: 4444
          resources: {}
      restartPolicy: Always
status: {}
